export const FETCH_FAVORITES_REQUEST = 'FETCH_FAVORITES_REQUEST';
export const FETCH_FAVORITES_SUCCESS = 'FETCH_FAVORITES_SUCCESS';
export const FETCH_FAVORITES_FAILURE = 'FETCH_FAVORITES_FAILURE';

export const ADD_FAVORITES_REQUEST = 'ADD_FAVORITES_REQUEST';
export const ADD_FAVORITES_SUCCESS = 'ADD_FAVORITES_SUCCESS';
export const ADD_FAVORITES_FAILURE = 'ADD_FAVORITES_FAILURE';

export const REMOVE_FAVORITES_REQUEST = 'REMOVE_FAVORITES_REQUEST';
export const REMOVE_FAVORITES_SUCCESS = 'REMOVE_FAVORITES_SUCCESS';
export const REMOVE_FAVORITES_FAILURE = 'REMOVE_FAVORITES_FAILURE';

export const FETCH_FAV_RECIPES_INFORMATION_FAILURE = 'FETCH_FAV_RECIPES_INFORMATION_FAILURE';
export const FETCH_FAV_RECIPES_INFORMATION_SUCCESS = 'FETCH_FAV_RECIPES_INFORMATION_SUCCESS';
export const FETCH_FAV_RECIPES_INFORMATION_REQUEST = 'FETCH_FAV_RECIPES_INFORMATION_REQUEST';