export const REGISTER_USER_REQUEST = 'REGISTER_USER_REQUEST';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_FAILURE = 'REGISTER_USER_FAILURE';
export const RESET_REGISTER_USER = 'RESET_REGISTER_USER';

export const LOGIN_USER_REQUEST = 'LOGIN_USER_REQUEST';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAILURE = 'LOGIN_USER_FAILURE';
export const RESET_LOGIN_USER = 'RESET_LOGIN_USER';
export const CLEANUP_LOGIN_USER = 'CLEANUP_LOGIN_USER';

export const SIGNOUT_USER = 'SIGNOUT_USER';



