export const FETCH_RECIPES_REQUEST = 'FETCH_RECIPES_REQUEST';
export const FETCH_RECIPES_SUCCESS = 'FETCH_RECIPES_SUCCESS';
export const FETCH_RECIPES_FAILURE = 'FETCH_RECIPES_FAILURE';

export const FETCH_RECIPES_BY_INGREDIENTS_REQUEST = 'FETCH_RECIPES_BY_INGREDIENTS_REQUEST';
export const FETCH_RECIPES_BY_INGREDIENTS_SUCCESS = 'FETCH_RECIPES_BY_INGREDIENTS_SUCCESS';
export const FETCH_RECIPES_BY_INGREDIENTS_FAILURE = 'FETCH_RECIPES_BY_INGREDIENTS_FAILURE';

export const FETCH_RECIPES_INFORMATION_REQUEST = 'FETCH_RECIPES_INFORMATION_REQUEST';
export const FETCH_RECIPES_INFORMATION_SUCCESS = 'FETCH_RECIPES_INFORMATION_SUCCESS';
export const FETCH_RECIPES_INFORMATION_FAILURE = 'FETCH_RECIPES_INFORMATION_FAILURE';
export const RESET_RECIPE_INFORMATION = 'RESET_RECIPE_INFORMATION';

export const SET_SEARCH_QUERY = 'SET_SEARCH_QUERY';
export const CLEAR_SEARCH_QUERY = 'CLEAR_SEARCH_QUERY';
